# Day 3 - Assignment Solution:

In [3]:
import numpy as np
print(np.__version__)
arr = np.arange(2,50,3)
print('The array starting from 2 till 50 with a stepsize of 3 is:',arr)
print(type(arr))

1.18.1
The array starting from 2 till 50 with a stepsize of 3 is: [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
<class 'numpy.ndarray'>


In [14]:
l1 = list(input('Enter 1st list of numbers:'))
l2 = list(input('Enter 2nd list of numbers:'))
l1 = np.array(l1)
l2 = np.array(l2)
print('1st Array:',l1)
print('---------------------------------------------------------------')
print('2nd Array:',l2)
print('---------------------------------------------------------------')
print(type(l1))
print('---------------------------------------------------------------')
print(type(l2))
print('---------------------------------------------------------------')
l3 = np.concatenate((l1,l2))
print('Concatenated Arrays are:',l3)
print('---------------------------------------------------------------')
print('1st Sorted Array:',np.sort(l1))
print('---------------------------------------------------------------')
print('2nd Sorted Array:',np.sort(l2))
print('---------------------------------------------------------------')
print('Resultant Sorted Array:',np.sort(l3))

Enter 1st list of numbers:37859
Enter 2nd list of numbers:98532
1st Array: ['3' '7' '8' '5' '9']
---------------------------------------------------------------
2nd Array: ['9' '8' '5' '3' '2']
---------------------------------------------------------------
<class 'numpy.ndarray'>
---------------------------------------------------------------
<class 'numpy.ndarray'>
---------------------------------------------------------------
Concatenated Arrays are: ['3' '7' '8' '5' '9' '9' '8' '5' '3' '2']
---------------------------------------------------------------
1st Sorted Array: ['3' '5' '7' '8' '9']
---------------------------------------------------------------
2nd Sorted Array: ['2' '3' '5' '8' '9']
---------------------------------------------------------------
Resultant Sorted Array: ['2' '3' '3' '5' '5' '7' '8' '8' '9' '9']


In [15]:
arr1 = np.ndarray([4,5,2])
print('The Array is:',arr1)
print('---------------------------------------------------------------')
print('Dimension of the Array is:',np.ndim(arr1))
print('---------------------------------------------------------------')
print('Size of the Array is:',np.size(arr1))

The Array is: [[[2.78199564e-312 2.78261950e-312]
  [2.78259676e-312 2.78280939e-312]
  [2.78280598e-312 2.78280598e-312]
  [2.78280597e-312 2.78280597e-312]
  [2.78279095e-312 2.78279094e-312]]

 [[2.78280620e-312 2.78280620e-312]
  [2.78281664e-312 2.78281664e-312]
  [2.78281671e-312 2.78281671e-312]
  [2.78280699e-312 2.78280700e-312]
  [2.78280700e-312 2.78281678e-312]]

 [[2.78281679e-312 2.78281679e-312]
  [2.78281679e-312 2.78281679e-312]
  [2.78281679e-312 2.78281679e-312]
  [2.78281679e-312 2.78281679e-312]
  [2.78281679e-312 2.78281710e-312]]

 [[2.78281710e-312 2.78281709e-312]
  [2.78281710e-312 2.78281693e-312]
  [2.78281692e-312 2.78281710e-312]
  [2.78281709e-312 2.78281710e-312]
  [2.78281693e-312 2.78281693e-312]]]
---------------------------------------------------------------
Dimension of the Array is: 3
---------------------------------------------------------------
Size of the Array is: 40


In [25]:
abc = np.arange(4)
print(abc.shape)
print(np.ndim(abc))
print('---------------------------------------------------------------')
abc1=abc[:,np.newaxis]
print(abc1)
print(abc1.shape)
print(np.ndim(abc1))
print('---------------------------------------------------------------')
abc2 = np.expand_dims(abc,axis=(0,2))
print(abc2)
print(abc2.shape)
print(np.ndim(abc2))

(4,)
1
---------------------------------------------------------------
[[0]
 [1]
 [2]
 [3]]
(4, 1)
2
---------------------------------------------------------------
[[[0]
  [1]
  [2]
  [3]]]
(1, 4, 1)
3


In [31]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])
print('Vertically Stacked Array:\n',np.vstack((ar1,ar2)))
print('Horizontally Stacked Array:\n',np.hstack((ar1,ar2)))

Vertically Stacked Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontally Stacked Array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [37]:
ar3 = np.array([2,3,5,6,7,4,3,5,6,4,3,3,6,78,2,3,4,3,3,2,2,55,77,222,78,99])
print('Original Array:\n',ar3)
print('---------------------------------------------------------------------------------')
ar4 = np.unique(ar3)
print('Unique Items from the Original Array:\n',ar4)
print('Count of Unique Items:',len(ar4))

Original Array:
 [  2   3   5   6   7   4   3   5   6   4   3   3   6  78   2   3   4   3
   3   2   2  55  77 222  78  99]
---------------------------------------------------------------------------------
Unique Items from the Original Array:
 [  2   3   4   5   6   7  55  77  78  99 222]
Count of Unique Items: 11
